### ISSUE TITLE
Add /selftimeout command

### ISSUE THREAD

**Issue by ivandardi** [rust-community-discord/ferrisbot-for-discord#6]
We need a command that will self timeout whoever calls it. It's been a necessity for a few members before, so adding it to the bot would be nice.

The command should be slash only so that the person calling it is sure that they're calling it, because the consequences are irreversible.

The `/selftimeout` command should take in a parameter called `duration`. That parameter should specify the duration of the self-timeout.

As for the implementation, it'd need to time-out the caller for the specified duration and then send a confirmation message saying "You've timeouted yourself. Please enjoy your time! If you've done this by mistake, please open a `/modmail reason:I've accidentally timeouted myself`". That message, and the whole command, should be ephemeral.

**Comment by whispersofthedawn** [comment]
> If you've done this by mistake, please open a `/modmail reason:I've accidentally timeouted myself``. That message, and the whole command, should be ephemeral.

Can you send slash commands if you're muted? I'm pretty sure you can't type in any channel, and thus cannot type a slash command invocation. I think it could be more helpful to have a DM command `/unselftimeout`, so the mods wouldn't have to deal with it either (especially in cases where it's not accidental). (Unless, of course, the point of having to go through mods is to make it irreversible for someone (presumably because this has to do with lack of self-control).)

**Comment by ivandardi** [comment]
Yes, that's kinda the point. I guess we could add a special button to the modmail channel to open a modmail for when people accidentally mute themselves. That works around the no-sending-message thing. They can still interact with buttons, right?

**Comment by ivandardi** [comment]
d0d49e3a8bc43ea99d1ec1a9c411c5bfacc00bb7 21933f786f4df00e125d2ec79ee5a6b2f0b36724 2bd9097132114f97c42f4b90fba65c5042f78f9b

The above are commits related to this feature. I consider it to be implemented now, so I'm closing this issue.
